# Generated by Django 4.1.6 on 2023-02-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0002_occasion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occasion',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='occasion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
