# Generated by Django 4.1.6 on 2023-02-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0004_itemtype_remove_occasion_category_occasion_itemtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='itemtype',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='occasion',
            name='itemtype',
        ),
    ]
