# Generated by Django 4.1.6 on 2023-02-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0005_rename_itemtype_itemtype_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='itemtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='occasion.itemtype'),
        ),
    ]
