# Generated by Django 4.1.6 on 2023-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occasion', '0006_occasion_itemtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='occasion',
            name='tags',
            field=models.ManyToManyField(to='occasion.tag'),
        ),
    ]
